spring.application.name=pdf-text-search


server.port=8012


spring.elasticsearch.uris=http://localhost:9200

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.upload.dir=C:/pdf_uploads